const jwt = require("jsonwebtoken")
const secretKey='functionUp';
const userAuth = function(req, res, next) {
    try {
        const token = req.headers.authorization; //setting token in the request header.
    //    console.log(token);           
        if (!token) {
            return res.status(403).send({ status: false, message: `Missing authentication token in request` })
        }

        let Bearer = token.split(' ')
        
        jwt.verify(Bearer[1], secretKey,function (err, data){
            if(err){ 
                return res.status(400).send({status:false, message:err.message})
            }
            else{
                req.userId = data.userId; //matching userId for which token generated by the userId provided in the request.
                next()
            }
           
        }
        );
        //decoding authentication token
      
    } catch (error) {
        return res.status(500).send({ status: false, message: error.message })
    }
}

module.exports.userAuth=userAuth;